source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KCExplodeTabBar_Example', :exclusive => true do
  pod "KCExplodeTabBar", :path => "../"
end

target 'KCExplodeTabBar_Tests', :exclusive => true do
  pod "KCExplodeTabBar", :path => "../"

  
end
